name: C++ CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build g++ lcov

      - name: Configure
        run: cmake -G Ninja -B build -DENABLE_COVERAGE=ON

      - name: Build
        run: ninja -C build

      - name: Run tests
        run: ./build/tests
      
      - name: Generate coverage report
        run: lcov --capture --directory build --output-file coverage.info --ignore-errors mismatch

      - name: Remove test files
        run: lcov --remove coverage.info '*/tests/*' -o coverage.info

      - name: Coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.info
          badge: true
          fail_below_min: false
          format: markdown
          output: both

      - name: Generate HTML coverage report
        run: genhtml coverage.info --output-directory coverage-html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-html
